# Generated by Django 3.2.4 on 2021-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='media/default_image.jpeg', upload_to=''),
        ),
    ]
