# Generated by Django 3.2.4 on 2021-06-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/default_image.jpeg', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
