# Generated by Django 3.2.4 on 2021-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210626_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runimage',
            name='image',
            field=models.ImageField(upload_to='out_images'),
        ),
    ]
